annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= 1.16.0-0'
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/rancher-version: '>= 2.7.0-0'
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
apiVersion: v2
appVersion: 0.1.0
description: Turkish Localization Extension for Rancher Manager
name: tr-locale
type: application
version: 0.1.0
icon: >-
  https://raw.githubusercontent.com/enterprisecoding-ltd/rancher-extensions-tr-locale/main/pkg/tr-locale/tr-locale.svg
